// pages/api/menu.ts

import { NextApiRequest, NextApiResponse } from 'next';

const menuItems = [
  {
    id: 1,
    name: 'Espresso',
    description: 'Strong and bold espresso shot.',
    category: 'Coffee',
    price: '$3.00',
    badge: 'Best Seller',
    calories: 5,
    dietary: ['Vegan'],
    available: true,
  },
  {
    id: 2,
    name: 'Latte',
    description: 'Smooth espresso with steamed milk.',
    category: 'Coffee',
    price: '$4.50',
    badge: '',
    calories: 120,
    dietary: ['Vegetarian'],
    available: true,
  },
  {
    id: 3,
    name: 'Iced Mocha',
    description: 'Chilled coffee with chocolate syrup and milk.',
    category: 'Coffee',
    price: '$5.00',
    badge: 'New',
    calories: 180,
    dietary: ['Vegetarian'],
    available: true,
  },
  {
    id: 4,
    name: 'Blueberry Muffin',
    description: 'Freshly baked muffin with blueberries.',
    category: 'Snacks',
    price: '$2.50',
    badge: 'Seasonal',
    calories: 250,
    dietary: ['Vegetarian'],
    available: true,
  },
  {
    id: 5,
    name: 'Vegan Banana Bread',
    description: 'Moist and delicious banana loaf, 100% vegan.',
    category: 'Snacks',
    price: '$3.00',
    badge: '',
    calories: 220,
    dietary: ['Vegan'],
    available: true,
  },
  {
    id: 6,
    name: 'Pumpkin Spice Latte',
    description: 'Seasonal favourite with warm spices.',
    category: 'Coffee',
    price: '$5.50',
    badge: 'Seasonal',
    calories: 210,
    dietary: ['Vegetarian'],
    available: true,
  },
  {
    id: 7,
    name: 'Avocado Toast',
    description: 'Fresh avocado on toasted sourdough.',
    category: 'Snacks',
    price: '$6.00',
    badge: 'Best Seller',
    calories: 330,
    dietary: ['Vegan'],
    available: true,
  },
  {
    id: 8,
    name: 'Chai Latte',
    description: 'Aromatic spiced tea with steamed milk.',
    category: 'Coffee',
    price: '$4.00',
    badge: '',
    calories: 130,
    dietary: ['Vegetarian'],
    available: false,
  },
  {
    id: 9,
    name: 'Almond Croissant',
    description: 'Flaky pastry with sweet almond filling.',
    category: 'Snacks',
    price: '$3.80',
    badge: '',
    calories: 290,
    dietary: ['Vegetarian'],
    available: true,
  },
  {
    id: 10,
    name: 'Matcha Latte',
    description: 'Earthy green tea blended with milk.',
    category: 'Coffee',
    price: '$4.20',
    badge: 'New',
    calories: 100,
    dietary: ['Vegetarian'],
    available: true,
  },
];

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  res.status(200).json(menuItems);
}
